{{- if .Values.caPassword.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "step-certificates.fullname" . }}-ca-password
  labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
type: Opaque
data:
  password: {{ .Values.caPassword.password | b64enc | quote }}
{{- end }}
