{{- if .Values.existingCerts.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "step-certificates.fullname" . }}-certs
  labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
data:
  {{- range $key, $value := .Values.existingCerts.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
