{{- if .Values.existingSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "step-certificates.fullname" . }}-secrets
  labels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
type: Opaque
data:
  {{- range $key, $value := .Values.existingSecrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
