{{- if .Values.stepConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "step-certificates.fullname" . }}-config
data:
  ca.json: |-
    {{(tpl .Values.stepConfig.configTemplate .) | fromYaml | toJson }}
{{- end }}
