# Default values for step-certificates
#https://github.com/smallstep/helm-charts/blob/master/step-certificates/values.yaml
step-certificates:
  image:
    repository: cr.smallstep.com/smallstep/step-ca-bootstrap
    tag: 0.25.3-rc7
